#
# Hugo global configuration
#
baseURL = 'https://bootstrap-validate.js.org/'
languageCode = 'en-us'
title = 'bootstrap-validate'
theme = 'hugo-theme-learn'

archetypeDir = 'site/archetypes'
assetDir = 'site/assets'
contentDir = 'site/content'
dataDir = 'site/data'
layoutDir = 'site/layouts'
staticDir = 'site/static'
themesDir = 'site/themes'
publishDir = 'docs'

#
# Geekdoc theme configuration
#
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 9

#
# bootstrap-validate configuration
#
[params]
geekdocBreadcrumb = false
geekdocRepo = 'https://github.com/PascaleBeier/bootstrap-validate'
geekdocEditPath = 'edit/main/site/content'
[params.versions]
'Bootstrap 3' = '/v1'
'Boostrap 4' = '/v2'
'Bootstrap 5' = '/v3'


[Languages]
[Languages.en]
title = "bootstrap-validate"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/PascaleBeier/bootstrap-validate"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-gift'></i> Support us with Developer Merch"
url = "https://devsfordevs.shop"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> Bootstrap 3"
url = "/v1"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> Bootstrap 4"
url = "/v2"
weight = 13
